USE [TMP]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Products](
	[ID] [int] NOT NULL,
	[CODE] [nvarchar](max) NOT NULL,
	[NAME] [nvarchar](max) NULL,
	[PRICE] [int] NULL,
	[CATEGORYID] [int] NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_ProductCategory_ProductID] FOREIGN KEY([CATEGORYID])
REFERENCES [dbo].[ProductCategory] ([ID])
ON DELETE CASCADE

